### ISSUE TITLE
Декомпозируй на компоненты, соблюдай SRP в компонентах

### ISSUE THREAD

**Issue by mordvinx** [Mikhail-Martynenko/todo-list-vue#1]
https://github.com/Mikhail-Martynenko/todo-list-vue/blob/3d67f3d2ff1ac84e0040084ecabd2d3d3d482dbf/src/App.vue#L4-L7

Это должен быть отдельный компонент, например `<InputWithAction @click="createTask" />`

`createTask(taskName: string)`

**Comment by mordvinx** [comment]
При этом состояние инпута можно хранить внутри `<InputWithAction />`, а не в `App`

**Comment by Mikhail-Martynenko** [comment]
Добавил компонент InputWithAction
